In [1]:
import pandas as pd
df = pd.read_csv("../../data/data-ml.csv")
df.head(5)

,id,country,year,yearly_score,goal1,goal2,goal3,goal4,goal5,goal6,...,goal8,goal9,goal10,goal11,goal12,goal13,goal14,goal15,goal16,goal17
0,AFG,Afghanistan,2020,"47,47",29.0,38,37,43,26,49,...,47,11,NaN,36,95,99,NaN,78,45,43
1,AFG,Afghanistan,2021,"46,27",20.0,38,35,35,29,50,...,45,11,NaN,34,95,99,NaN,78,45,43
2,AFG,Afghanistan,2019,"46,13",30.0,40,36,43,24,45,...,46,11,NaN,35,95,99,NaN,65,46,41
3,AFG,Afghanistan,2022,"45,60",17.0,38,36,35,18,51,...,43,17,NaN,35,96,99,NaN,77,42,43
4,AFG,Afghanistan,2018,"45,53",30.0,41,37,41,21,42,...,47,11,NaN,33,95,99,NaN,65,46,41

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Instantiate a Sequential model
model = Sequential()

# Add a Dense layer with 50 neurons and an input of 1 neuron
model.add(Dense(50, input_shape=(1,), activation='relu'))

# Add two Dense layers with 50 neurons and relu activation
model.add(Dense(50,activation='relu'))
model.add(Dense(50,activation='relu'))

# End your model with a Dense layer and no activation
model.add(Dense(1))
# Compile your model
model.compile(optimizer = 'adam', loss = 'mse')

print("Training started..., this can take a while:")

# Fit your model on your data for 30 epochs
model.fit(features,labels, epochs = 30)

# Evaluate your model 
print("Final loss value:",model.evaluate(features, labels))